### ISSUE TITLE
correction

### ISSUE THREAD

**Issue by rjwang** [rjwang/DMHiggsAnalysis#11]
please correct the pointer type of branch mu and initWeight,  i.e.
https://github.com/rjwang/DMHiggsAnalysis/blob/master/Root/DMHiggsAnalysis.cxx#L60
to 
myEvents->Branch("initWeight",&initWeight_var,"initWeight_var/F");

https://github.com/rjwang/DMHiggsAnalysis/blob/master/Root/DMHiggsAnalysis.cxx#L58
to 
myEvents->Branch("mu",&mu_var,"mu_var/F");

**Comment by rjwang** [comment]
@alopezso

**Comment by alopezso** [comment]
Done
