### ISSUE TITLE
photon isolation bug 

### ISSUE THREAD

**Issue by rjwang** [rjwang/DMHiggsAnalysis#16]
following branches in the ntuple tree are always zero, please find the reason. 

  photon_isIsoFixedCutTight;
  photon_isIsoFixedCutTightCaloOnly;
  photon_isIsoFixedCutLooseCaloOnly;

https://github.com/rjwang/DMHiggsAnalysis/blob/master/Root/DMHiggsAnalysis.cxx#L502-L505

**Comment by alopezso** [comment]
Solved !! In the declaration of the different SG::AuxElement::Accessor for the isolation cuts, I declare isiso.. ("isiso...") . Inside the parentheses, we should have the 'isIso...' .

I will commit the changes now.
