### ISSUE TITLE
Bug in runSelection

### ISSUE THREAD

**Issue by alopezso** [rjwang/DMHiggsAnalysis#17]
Yesterday I had a problem with runSelection. The problem is in line :

 HG::StrV Files = HG::parseArguments(&runProcess, argc, argv);

It seems that my compiler does no recognize the method parseArgument as belonging to the HG namespace.

If I deleted the HG:: part, it could not recognize the parseArgument method neither. So I think that the problem is that it cannor use this method. Culd you please check if you have the same problem ?

**Comment by blaforge** [comment]
Hi Alvaro,
do you have all the include file needed ? It is usually related to a bad include or to a unfortunate "using namespace ..." which mask the proper namespace.
cheers,
Bertrand

**Comment by alopezso** [comment]
Hi Bertrand,

Yes in the runSelection there there is RunUtils.h. It is true that the definition in the .cxx is not done using RunUtils::parseArguments but I think that the .cxx should be included too in the compilation, doesn't it ? 
Alvaro

**Comment by rjwang** [comment]
Aha, please update HGamAnalysisFramework with following two files:
https://github.com/rjwang/HGamAnalysisFramework/blob/master/HGamAnalysisFramework/RunUtils.h
https://github.com/rjwang/HGamAnalysisFramework/blob/master/Root/RunUtils.cxx

**Comment by alopezso** [comment]
Done !
