### ISSUE TITLE
No gamma jet Sherpa cross-sections

### ISSUE THREAD

**Issue by alopezso** [rjwang/DMHiggsAnalysis#19]
It seems that in the ATLAS twiki for cross-sections, Pythia8 simulated gamma jet samples are eliminated (no cross-section). Furthermore, it seems that there was a problem with Sherpa cross-section in version 2.1:https://twiki.cern.ch/twiki/bin/view/AtlasProtected/CentralMC15ProductionList#Gamma_jet_Sherpa_2_1_1_x_section

Moreover, those samples were sliced depending on the filter used in MC to cut certain type of quarks in the loop (Cfilter,Bfilter,CVeto,BVeto). In the MxAODs, we just have the samples sliced in pT of the photon

**Comment by rjwang** [comment]
please find the cross section here:
https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/HiggsPhys/Run2/HGamma/xAOD/HGamAnalysisFramework/trunk/data/MCSamples.config
